### ISSUE TITLE
Max Peer Review

### ISSUE THREAD

**Issue by MaxLindberg** [teokem/responseStudies-alex-exook#2]
Very impressive! Extremely well documented, both for the science and the code (also nice with mentions about some of the warnings that you get so you know not to worry). Straightforward to reproduce. Utilizes pandas to both read, manipulate and write data.  Outputs nice vector graphics with sufficiently large fonts and labels (185 mm wide instead of the instructed 183 mm but I definitely consider that close enough). Also a Zenodo DOI.

Checks all the requirements, well done!

**Comment by exook** [comment]
Thank you for the kind feedback! Well done for finding the 185 vs 183 mm error, this will be a good exercise in handling a reported issue :) I will make a commit with the necessary fix and come back here.

**Comment by exook** [comment]
I made a new branch, fixed the values, pushed the new branch to github, made a merge request, linked this issue to the merge request. Then the issue closed automatically when the merge was done :)

**Comment by MaxLindberg** [comment]
Great! Managed to test the whole github workflow ;)
